### ISSUE TITLE
Compilation to JavaScript

### ISSUE THREAD

**Issue by danr** [cpitclaudel/z3.wasm#3]
Hi, did you test compiling to JavaScript (or asm.js)? I'm wondering what the trade-off is between startup-time and verification-time. I'm ok with a magnitude verification speed loss if loading the library and starting it is less than a second.

**Comment by danr** [comment]
On that note, do you know of any ways to compile only parts of Z3 (or CVC4)? Right now I have a project where I would only need the smtlib parser, the sat solver and real linear arithmetic. The rest will be unused.

**Comment by cpitclaudel** [comment]
I did try asm.js; in fact, the scripts in this repo can do that too.  IIRC, the demo page also has a JS fallback, so you could try to disable wasm in your browser and see if it loads the JS.  I think the performance loss was not as bad as a 10x.

But! IIRC, parsing javascript wasn't much faster than parsing WASM.

**Comment by cpitclaudel** [comment]
Not sure about subsetting; I think there are compilation flags that you could tweak.

**Comment by cpitclaudel** [comment]
Also, regarding WASM: I think there's now technology to cache compiled WASM code, so things should be much snappier if set up properly after the first visit.

**Comment by danr** [comment]
Thanks for your reply! I didn't actually find a JS version at https://people.csail.mit.edu/cpitcla/z3.wasm/ but I think I will drop that. I will move the discussion about subset compliatio to the z3 issue tracker instead.

Thanks again!
