### ISSUE TITLE
Wget emscripten fails to download

### ISSUE THREAD

**Issue by Cypher1** [cpitclaudel/z3.wasm#4]
Recently tried to run this project but found that the set up no longer works. I believe this is because the portable emsdk file has been moved.

I get the following error when running `./z3.sh`
```
*******************
*** Downloading ***
*******************
* wget emscripten
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
```

Can we change this to use a git checkout?

**Comment by cpitclaudel** [comment]
Thanks, great point.  Do you want to make a PR?

**Comment by Cypher1** [comment]
I want to but had some trouble implementing the change myself. Some of the files seem to be missing or moved from emscripten's HEAD. Will see if I have time to work this out myself (as this is planned to be used in a value add [non-core] feature).

**Comment by cpitclaudel** [comment]
I might look at it otherwise, but it could take time.  Please ping me in ~a week if you haven't had time ^^

**Comment by Cypher1** [comment]
Ping, filed an issue with the emscripten team to see if we can just get an alternative URL rather than having to work out all the set up (presumably we're not the only ones who would like to avoid that complexity), no change yet but they seem interested.

https://github.com/emscripten-core/emscripten/issues/6288

**Comment by Cypher1** [comment]
Sorry wrong button

**Comment by cpitclaudel** [comment]
Thanks, let's see how that turns out. Otherwise I'll take the time to fix the script
